AllCops:
  NewCops: enable
  Exclude:
    - vendor/**/*

Metrics:
  Enabled: false

Layout/LineLength:
  Max: 256
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-rake
  - rubocop-rspec

require:
  - rubocop-capybara

